#!/usr/bin/env bash
#
# Inject the portfolio add-on tags into index.html, idempotently.
#
# Re-exporting the site from Claude Design overwrites index.html and wipes the
# add-ons. Re-running this script puts them back. Running it twice is a no-op:
# any existing block is stripped before a fresh one is inserted.
#
#   ./scripts/inject.sh [target-html]

set -euo pipefail

cd "$(dirname "$0")/.."

TARGET="${1:-index.html}"
BEGIN_MARK='<!-- BEGIN portfolio-addons -->'
END_MARK='<!-- END portfolio-addons -->'

[ -f "$TARGET" ] || { echo "error: '$TARGET' not found" >&2; exit 1; }

# Strip a previous block, if any.
if grep -qF "$BEGIN_MARK" "$TARGET"; then
  # Consume the block plus its own trailing newline — but NOT the newline that
  # ends the preceding line, or that line would merge with </body>.
  perl -0pi -e "s/\Q${BEGIN_MARK}\E.*?\Q${END_MARK}\E\n?//s" "$TARGET"
  echo "  removed previous add-on block"
fi

# The bundle stores the site's own markup as an escaped string (</body> appears
# there as </body>), so exactly one literal </body> should remain: the real
# one. If that ever stops being true, stop rather than guess.
count=$(grep -c '</body>' "$TARGET" || true)
if [ "$count" -ne 1 ]; then
  echo "error: expected exactly 1 literal </body> in '$TARGET', found $count." >&2
  echo "       The bundle format may have changed — inspect before injecting." >&2
  exit 1
fi

anchor=$(grep -n '</body>' "$TARGET" | cut -d: -f1)
tmp=$(mktemp)

head -n "$((anchor - 1))" "$TARGET" > "$tmp"
cat >> "$tmp" <<EOF
${BEGIN_MARK}
<!-- Generated by scripts/inject.sh — do not edit by hand.
     These tags are destroyed when the bundle swaps the document root, but the
     code they load only touches window, which survives. See assets/claude-shim.js. -->
<script src="assets/config.js"></script>
<script src="assets/claude-shim.js"></script>
${END_MARK}
EOF
tail -n "+${anchor}" "$TARGET" >> "$tmp"

mv "$tmp" "$TARGET"
echo "  injected add-on block into '$TARGET' before line $anchor"

# --- Enable the "Ask AI" button -------------------------------------------
#
# The design renders its chat trigger inside <sc-if value="{{ showAskAi }}">,
# but the component hardcodes `showAskAi: false` instead of reading the prop:
#
#     showBlog:  this.props.showBlog ?? false,   <- reads the prop
#     showAskAi: false,                          <- ignores it
#
# The prop schema declares default:true and exposes a toggle in Claude Design,
# so that toggle silently does nothing. Until this is fixed upstream in the
# design itself, flip the literal here. Exactly one occurrence exists, so the
# replacement is unambiguous.
if grep -qF 'showAskAi: true' "$TARGET"; then
  echo "  'Ask AI' button already enabled"
elif [ "$(grep -c 'showAskAi: false' "$TARGET")" -eq 1 ]; then
  perl -0pi -e 's/showAskAi: false/showAskAi: true/' "$TARGET"
  echo "  enabled the 'Ask AI' button (showAskAi: false -> true)"
else
  echo "  WARNING: could not find a unique 'showAskAi: false' to patch." >&2
  echo "           The chat trigger may not render. Check the design output." >&2
fi

# --- Enable the ⌘K / Ctrl+K chat shortcut ---------------------------------
#
# The chat footer advertises "K toggles", but the handler is dead-coded:
#
#     if (false && (e.key === 'k' || e.key === 'K') && (e.metaKey || e.ctrlKey || !typing))
#
# Dropping the `false &&` restores the design's intended behaviour: ⌘K/Ctrl+K
# anywhere, plus bare "k" when the user is not typing in a field.
if grep -qF "if ((e.key === 'k'" "$TARGET"; then
  echo "  chat keyboard shortcut already enabled"
elif [ "$(grep -c "if (false && (e.key === 'k'" "$TARGET")" -eq 1 ]; then
  perl -0pi -e "s/\Qif (false && (e.key === 'k'\E/if ((e.key === 'k'/" "$TARGET"
  echo "  enabled the chat keyboard shortcut (⌘K / Ctrl+K)"
else
  echo "  WARNING: could not find the disabled 'k' shortcut guard to patch." >&2
fi

# --- Hide the job-description claim ---------------------------------------
#
# The chat header advertises "paste a job description to see the match", but the
# Worker's system prompt gives no job-description matching instruction, so the
# behaviour is uninstructed rather than designed. Drop the claim until the
# feature is deliberately built. Re-enable by restoring the phrase here and
# adding a JD-matching rule to SYSTEM_PROMPT in the Worker.
#
# The pattern MUST be a fixed string (\Q...\E). A regex with quantifiers such as
# `\s*\S+\s*paste a job description...` backtracks catastrophically against this
# file, whose bundle payload is a single ~2 MB line, and never terminates.
if grep -qF 'paste a job description' "$TARGET"; then
  perl -0pi -e 's/\Q · paste a job description to see the match\E//' "$TARGET"
  echo "  removed the 'paste a job description' claim from the chat header"
else
  echo "  job-description claim already removed"
fi
